Vis and stats for TFR analysis
ktavabi/badbaby pull request #5
Opened 2020-09-21 19:05 UTC by pettetmw

Here is the code for the latest group visualizations and stats, please note that we are working on dataset-tone branch, not master.
I've tried creating a jupyter notebook from tfr_pipe.py, but I cant get the server to run correctly on Colchuck, and the ipynb file doesn't open on github either.  So that's not done, but I guess we should meet since I have no idea how to figure out that problem.

2020-09-22 21:02 UTC, ktavabi requested changes
Considering this repo is not an application I'd like to see a few improvements to this commit before merging. 

- [x] Convert extensive comments to _useful_ notes chunk in the docstring at the top.
- [ ] Lose the local (MATLAB like) [functions](https://github.com/ktavabi/badbaby/pull/5/files#diff-49ef6ddbc0e3ab12d5e9e19d65d828d9R25) and just write out the few lines of code.
- [ ] commit only the files I or someone else needs to run on the data. 
- [ ] Archive junk [files](badbaby/python/fdrgist.py) and [extended commented sections](https://github.com/ktavabi/badbaby/pull/5/files#diff-49ef6ddbc0e3ab12d5e9e19d65d828d9R285)

2020-09-22 21:03 UTC, ktavabi commented on badbaby/python/Makefile
> +
Is this file necessary for scripts to run on dataset on another WS?

2020-09-24 23:20 UTC, pettetmw commented on badbaby/python/Makefile
> +
Nope, deleted in this commit

2020-09-24 23:23 UTC, pettetmw commented
This notebook should be able to build everything from original tone data directory.  See the section on path and file names.

2020-12-04 06:50 UTC, ktavabi commented
@pettetmw let's break this notebook up into a script per cell; starting with  

- [ ] write_subject_tfrs.py
- [ ] viz_grp_assr.py that also write TIDY csv

In the process, you can work on not repeating yourself in code, and I can move towards BIDS compliance in a modular fashion.

2020-12-09 20:59 UTC, pettetmw commented
@ktavabi ,  Revising repetitive code should be straightforward enough.  About file saving loop, I have a couple of questions:

Data returned by TFR_Morlet are of type AverageTFR and EpochsTFR, which differ from the Evoked and Epochs types in the two key features:

1) They are saved as hd5.
2) They are not represented in MNEFUN file system tree; the closest match I could find in mnefun:write_epochs.py was the following:

    for si, subj in enumerate(subjects):
        epochs_dir = op.join(p.work_dir, subj, p.epochs_dir)
        evoked_dir = op.join(p.work_dir, subj, p.inverse_dir)

Since there is no established mnefun convention, I guess we can create a dedicated folder.  LMK what you prefer.

Also, please specify what's going to be in "picks" in the new loop? IDs, filenames, full paths?

2020-12-10 07:23 UTC, ktavabi commented
@pettetmw
>They are saved as hd5.

If your output is a NumPy array then you can use either [`EvokedArray`](https://mne.tools/stable/generated/mne.EvokedArray.html?highlight=evoked%20array#mne.EvokedArray) to create an evoked or [`info`](https://mne.tools/stable/generated/mne.Info.html?highlight=info#mne.Info) along with `Epochs` class to clobber together an epochs object with the said array. The `hd5` format is a hangnail from when I was tooling around with `XDAWN`.

2020-12-10 19:41 UTC, pettetmw commented
Sorry, I failed to specify: `.hd5` is the file type used by `mne.time_frequency.write_tfrs()` and `mne.time_frequency.read_tfrs()`, and also by the `save()` methods of the AverageTFR and EpochsTFR classes.  (I'm not sure what connection to `XDAWN` is?).
I'm not sure if that changes anything, but I just want to confirm: the scripts should coerce the data from `AverageTFR` object into `Evoked` object and save as `.evo` file, and vice-versa to read back again? Or should I stick with TFR save/read functions and `.hd5` files?
Also, do you want these in the `inverse_dir` with other evo files?

2020-12-10 20:13 UTC, ktavabi commented
Forget what I said about `XDAWN`. Also, we should ditch `hd5`,  it's overkill for what we need: an `ipynb` at the end of the day that will run and print the figure in the manuscript so that any idiot with two thumbs and a keyboard can press `return` and get on their screen. To that end we need `Epoch` and `Evoked` class objects that once you have an array of values N-channels by N-time samples maybe reverse enginered and saved alongside the subject's `epochs` and `evoked` files on disk. Savvy?

2020-12-17 00:31 UTC, pettetmw commented
Question regarding `write_subject_tfrs.py` and `viz_grp_assr.py`: Can I assume that `tfr_group.ipynb` notebook will reside and be executed in context where the following statements (or similar) lead to correct construction of mnefun filename?:

>include badbaby
>...
>% and later, e.g.,
>filename = op.join(defaults.datadir, subj, 'inverse','Oddball_%d-sss_eq_%s-ave.fif' % (lp, subj))

In particular, how should the path in `defaults.datadir` be made available? If not via `include badbaby`, should I instead use a string variable hard-coded to explicit `datadir` path?

2020-12-17 17:58 UTC, pettetmw commented
(I enjoy these little conversations I have with myself :smile:)

2020-12-17 18:59 UTC, ktavabi commented
I can tell you're just as fucked in the head as I am..😂

2020-12-18 06:52 UTC, ktavabi commented
@pettetmw [Fig-SensorSpace.py](https://github.com/ktavabi/badbaby/commit/773467124c3183ab57c35fcf87640d0da778596c) in the Mismatch branch is what we need to aim for on the ASSR.

2020-12-18 18:46 UTC, pettetmw commented
Do I need to `pip install -e badbaby` into my `mne` environment (or something similar) for `import badbaby` to work?

2020-12-21 08:45 UTC, ktavabi commented
Yes

Sent from my iPhone

> On Dec 18, 2020, at 10:47 AM, pettetmw <notifications@github.com> wrote:
> 
> ﻿
> Do I need to pip install -e badbaby into my mne environment (or something similar) for import badbaby to work?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-23 18:38 UTC, pettetmw commented
@ktavabi or @larsoner , I just noticed that my TFR calculation is reading `All_*-epo.fif`, which presumably contains "All" the epochs, not just the AM tone epochs that I want.  Can you point me to an example of how to pick the latter from the former, once I've read the file?

2021-07-23 18:44 UTC, larsoner commented
`epochs['tone']` probably

https://mne.tools/dev/auto_tutorials/epochs/10_epochs_overview.html#subselecting-epochs

2021-07-23 22:52 UTC, pettetmw commented
@ktavabi , `badbaby/processing/write_sbj_tfrs.py` approaches the "idiot with two thumbs" benchmark.  You'll need to be not-an-idiot enough to modify the value of `datadir` variable.  Individual `epochs` and `inverse` dirs will be populated with `-tfr.h5` files of TFR data. (h5 not optional if we want the frequency dimension). The cell at the end of the script will read all of these and create tidy csv.  Please LMK if it runs correctly for you.  If so, then we can revise if needed, and start adding code to visualize summaries?

2021-08-17 06:51 UTC, ktavabi commented
@pettetmw I am cherry-picking gists from this PR into #19 and try to get it working on the database structure we've discussed in the past.

2021-08-17 07:08 UTC, ktavabi commented on badbaby/processing/write_sbj_tfrs.py
> +
Begin-cherry-pick

2021-08-17 07:09 UTC, ktavabi commented on badbaby/processing/write_sbj_tfrs.py
> +
end cherry-pick

2021-08-17 07:10 UTC, ktavabi commented on badbaby/processing/write_sbj_tfrs.py
> +        sids = [ os.path.basename(sidp)[-23:-16] for sidp in sidps ] # get id from full path
This is ugly

2021-08-17 07:14 UTC, ktavabi commented on badbaby/processing/write_sbj_tfrs.py
> +
I am not quite sure what this cell does, but it's rather hard to read and has some exemplary bad variable naming.

2021-08-17 07:36 UTC, ktavabi commented on badbaby/processing/write_sbj_tfrs.py
> +tfr_tag = '-tfr'
unnecessary

2021-08-17 07:42 UTC, ktavabi commented on badbaby/processing/write_sbj_tfrs.py
> +        tfr = [ [ '-tfr-epo', '-pow-epo', '-pow-evo', '-itc-evo', '-hot-evo', '-t2c-evo'],
This is unorthodox. Python lists are mutable and not ideal as containers for ND data.

2021-08-17 07:47 UTC, ktavabi commented on badbaby/processing/write_sbj_tfrs.py
> +        tNTrl, tNCh, tNFrq, tNS = tfr_epo.data.shape
DRY

2021-08-17 07:47 UTC, ktavabi commented on badbaby/processing/write_sbj_tfrs.py
> +        tNTrl, tNCh, tNS = epo.get_data().shape
What the 🤬 does `t` stand for?

2021-08-17 07:49 UTC, ktavabi commented on badbaby/processing/write_sbj_tfrs.py
> +        sids = [ os.path.basename(sidp)[-23:-16] for sidp in sidps ] # get id from full path
💩💩💩

2021-08-17 07:51 UTC, ktavabi reviewed
This definitely doesn't work on my end without editing. TBC

2021-08-17 07:52 UTC, ktavabi commented
> @pettetmw I am cherry-picking gists from this PR into #19 and try to get it working on the database structure we've discussed in the past.

2021-08-17 07:52 UTC, closed without merging

2021-08-19 21:44 UTC, pettetmw commented on badbaby/processing/write_sbj_tfrs.py
> +        sids = [ os.path.basename(sidp)[-23:-16] for sidp in sidps ] # get id from full path
why stop at three?

2021-08-19 21:51 UTC, pettetmw commented on badbaby/processing/write_sbj_tfrs.py
> +        sids = [ os.path.basename(sidp)[-23:-16] for sidp in sidps ] # get id from full path
@ktavabi, Just for my reference, is it the whole thing, or just line 127?  I really don't know how to name these files in an MNE-compliant way, so I could use some more specific guidance than poop emojis.

2021-08-19 22:06 UTC, pettetmw commented on badbaby/processing/write_sbj_tfrs.py
> +        tNTrl, tNCh, tNFrq, tNS = tfr_epo.data.shape
I thought an implementation like yours would be more appropriate, but didn't get around to it... my bad.  I like the way you wrote it.

2021-08-19 22:06 UTC, pettetmw commented on badbaby/processing/write_sbj_tfrs.py
> +        tfr = [ [ '-tfr-epo', '-pow-epo', '-pow-evo', '-itc-evo', '-hot-evo', '-t2c-evo'],
good catch

2021-08-19 22:19 UTC, ktavabi commented on badbaby/processing/write_sbj_tfrs.py
> +        sids = [ os.path.basename(sidp)[-23:-16] for sidp in sidps ] # get id from full path
It's the whole thing, Mark, the setup is different from upstream granted, but I couldn't get it to work with a list of subjects. For naming anything in general, to make it compliant, you tack on `-tfr`. What you've done here is just asking for trouble in any circumstance. 
Also, it's taken way too long to get to here with the guidance I've provided so far, despite the constraint with emojis.

2021-08-20 16:16 UTC, pettetmw commented on badbaby/processing/write_sbj_tfrs.py
> +        sids = [ os.path.basename(sidp)[-23:-16] for sidp in sidps ] # get id from full path
Agreed.  For the record, I don't object to the emojis.  If the code doesn't work and isn't readable enough for you to debug, then three poops is being generous.