WIP: Attempt to run
ktavabi/badbaby pull request #6
Opened 2020-12-14 19:16 UTC by larsoner

2020-12-14 19:20 UTC, larsoner commented on badbaby/processing/run_mnefun.py
> +work_dir = defaults.datadir
var missing without this change

2020-12-14 19:20 UTC, larsoner commented on badbaby/processing/run_mnefun.py
> +df.drop(df[df.index.isin(pd.Series(exclude, dtype=int))].index, inplace=True)
pandas warning about `object` being the new default

2020-12-14 19:20 UTC, larsoner commented on badbaby/processing/run_mnefun.py
> +from badbaby.defaults import return_dataframes
maybe you had a namespace change?

2020-12-14 19:20 UTC, larsoner commented on badbaby/defaults.py
> +exclude = []
this var was missing without this line

2020-12-14 19:20 UTC, larsoner commented on badbaby/processing/run_mnefun.py
> +            continue
Just for testing, try to process 117b

2020-12-14 19:21 UTC, larsoner commented
After `pip install -ve .` in the `badbaby` dir, running this I get:
```
python -u badbaby/processing/run_mnefun.py 
    
Using 1200 Hz as sampling rate and
    MEG0113 as ECG surrogate...
    13  Subjects:  ['101', '102', '103', '104', '105', '203', '205', '207', '208a', '209a', '301a', '921a', '925a']
    
Using 1200 Hz as sampling rate and
    MEG0143 as ECG surrogate...
    1  Subjects:  ['302a']
    
Using 1800 Hz as sampling rate and
    MEG0111 as ECG surrogate...
    3  Subjects:  ['116a', '122a', '212']
    
Using 1800 Hz as sampling rate and
    MEG0113 as ECG surrogate...
    24  Subjects:  ['113', '114', '120b', '122b', '124a', '125a', '127a', '131b', '211a', '213', '214', '215b', '223a', '223b', '224a', '226b', '228a', '229a', '309a', '310a', '310b', '921b', '923b', '925b']
    
Using 1800 Hz as sampling rate and
    MEG0141 as ECG surrogate...
    5  Subjects:  ['108', '118', '224b', '225b', '312b']
    
Using 1800 Hz as sampling rate and
    MEG0143 as ECG surrogate...
    22  Subjects:  ['109', '110', '117a', '119b', '123a', '127b', '128a', '128b', '130a', '131a', '209b', '211b', '215a', '218a', '220a', '225a', '231b', '311a', '311b', '312a', '314a', '316b']
Pulling raw files from acquisition machine. 
  Checking for proper remote filenames for bad_117a...
('', '')
Traceback (most recent call last):
  File "badbaby/processing/run_mnefun.py", line 170, in <module>
    mnefun.do_processing(
  File "/home/larsoner/mne_data/mnefun/mnefun/_mnefun.py", line 526, in do_processing
    outs[ii] = func(p, subjects, run_indices)
  File "/home/larsoner/mne_data/mnefun/mnefun/_fetching.py", line 39, in fetch_raw_files
    stdout_ = run_subprocess(
  File "<decorator-gen-2>", line 24, in run_subprocess
  File "/home/larsoner/python/mne-python/mne/utils/misc.py", line 166, in run_subprocess
    raise subprocess.CalledProcessError(p.returncode, command, output)
subprocess.CalledProcessError: Command '['ssh', '-p', '22', 'kasga.ilabs.uw.edu', 'find /brainstudio/bad_baby -type f -regex .*bad_117a_mmn_raw-?[0-9]*.fif$2>&1 | grep -v "Permission denied"']' returned non-zero exit status 1.
```

2020-12-14 19:29 UTC, ktavabi commented on badbaby/processing/run_mnefun.py
> +work_dir = defaults.datadir
This is where `ACQ` files reside locally?

2020-12-14 19:31 UTC, ktavabi commented on badbaby/processing/run_mnefun.py
> +df.drop(df[df.index.isin(pd.Series(exclude, dtype=int))].index, inplace=True)
This doesn't do anything unless `excludes` is amended in `defaults`

2020-12-14 19:35 UTC, larsoner commented on badbaby/processing/run_mnefun.py
> +work_dir = defaults.datadir
You tell me :) I assumed that it is -- the key is that `datapath` is not a var in `defaults.py` but `datadir` is, hence why I had to change it to get it to run without an `AttributeError`

2020-12-15 21:33 UTC, ktavabi requested changes
@larsoner Thanks this looks good! Just the documentation notes and merge when ready.

2020-12-15 21:33 UTC, ktavabi commented on badbaby/processing/score.py
>  from __future__ import print_function
Is this considered `<3.0` backwards compatiable? Any reason I need it?

2020-12-15 21:33 UTC, ktavabi commented on badbaby/processing/score.py
> +                # tone/1 or IDS/2 or syllable/3
Is this naming form `DACQ` settings?

2020-12-15 21:33 UTC, ktavabi commented on badbaby/processing/score.py
> +                off_minutes = abs((t_raw - t_tab).total_seconds() / 60.)
Is this the variable `offset` between `expyfun` and `acq`?

2020-12-15 21:33 UTC, ktavabi commented on badbaby/processing/score.py
> +            assert sum(good) == 1, sum(good)
Can you #comment what 65-67 does?

2020-12-15 21:33 UTC, ktavabi commented on badbaby/processing/score.py
> +                    header['session'] == '3'
`header['session'] == '3'` is likely to fail in cases where session order was reordered to enhance subject cooperation.

2020-12-15 21:33 UTC, ktavabi commented on badbaby/processing/score.py
Also summarize 71-74 and we can collapse into `docstring` with previous gist.

2020-12-15 21:49 UTC, ktavabi commented on badbaby/processing/run_mnefun.py
> +df.drop(df[df.index.isin(pd.Series(exclude, dtype=int))].index, inplace=True)
86 this. Once things are cleaned up I'll refactor `return_dataframes`.

2020-12-17 21:39 UTC, ktavabi commented on badbaby/processing/run_mnefun.py
> +            # Set the niprov handler to deal with events:
We can 86 improv

2020-12-18 14:54 UTC, larsoner commented on badbaby/processing/score.py
> +                # tone/1 or IDS/2 or syllable/3
It's what I observed in the expyfun headers in the .tab files

2020-12-18 14:54 UTC, larsoner commented on badbaby/processing/score.py
>  from __future__ import print_function
2.7 is ancient we can just kill it. I'm using `f` syntax that requires 3.6+ anyway...

2020-12-18 14:55 UTC, larsoner commented on badbaby/processing/score.py
> +                off_minutes = abs((t_raw - t_tab).total_seconds() / 60.)
Yep, will add comment

2020-12-18 15:57 UTC, larsoner commented
Requires https://github.com/LABSN/mnefun/pull/316

2020-12-18 20:19 UTC, ktavabi commented on badbaby/processing/score.py
> +                # tone/1 or IDS/2 or syllable/3
`tone`, `IDS`, `syllable` are what I referred to as the primary stimuli for the sessions. I was just curious how they would get into the `.tab` header. Presumably inherited from `DACQ` or more likely the session `expyfun.py`.

2020-12-18 20:28 UTC, larsoner commented on badbaby/processing/score.py
> +                # tone/1 or IDS/2 or syllable/3
Indeed the first line of `.tab` is a `# {...}` that has these values

2020-12-23 01:27 UTC, merged